/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package plantasvszombis;

import java.io.File;
import Estructuras.*;
import javax.swing.*;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Erick
 */
public class MenuCreacionPlantas extends javax.swing.JFrame {

    /**
     * Creates new form MenuCreacionPlantas
     */
    public String pathactual;
    public nodo_planta nuevaplanta;
    public int mostradorx;
    public int mostradory;
    
    public MenuCreacionPlantas() {
        initComponents();
        for(int x=1;x<100;x++){
        lista_defensa.addItem(x);
        lista_ataque.addItem(x);
        mostradorx=10;
        mostradory=10;
     
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        imagenaqui = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nombre_planta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lista_ataque = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        lista_defensa = new javax.swing.JComboBox();
        boton_imagen = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lista_tipo = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        Mostrador = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PlantasVsZombis 1.0.0");
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel2.setText("Imagen");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 20, 70, 30);

        imagenaqui.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.add(imagenaqui);
        imagenaqui.setBounds(320, 20, 90, 80);

        jLabel4.setText("Nombre");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 80, 70, 30);
        jPanel1.add(nombre_planta);
        nombre_planta.setBounds(120, 80, 160, 30);

        jLabel5.setText("Puntos de Ataque");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 120, 100, 30);

        jPanel1.add(lista_ataque);
        lista_ataque.setBounds(120, 130, 120, 20);

        jLabel6.setText("Puntos de Defensa");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 160, 100, 30);

        jPanel1.add(lista_defensa);
        lista_defensa.setBounds(120, 170, 120, 20);

        boton_imagen.setText("Elegir Imagen");
        boton_imagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_imagenActionPerformed(evt);
            }
        });
        jPanel1.add(boton_imagen);
        boton_imagen.setBounds(120, 20, 160, 40);

        jLabel7.setText("Tipo de  Ataque");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 200, 100, 30);

        lista_tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Disparador", "Ataque Directo" }));
        jPanel1.add(lista_tipo);
        lista_tipo.setBounds(120, 210, 120, 20);

        jButton1.setText("Crear Personaje");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(320, 190, 130, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 70, 530, 240);

        jLabel1.setText("Menú De Creación de Personajes  Plantas");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 10, 340, 50);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        jLabel3.setText("Imagen");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 330, 90, 30);

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        jLabel8.setText("Nombre");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(150, 330, 90, 30);

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        jLabel9.setText("Ataque");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(300, 330, 70, 30);

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        jLabel10.setText("Defensa");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(440, 330, 70, 30);

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        jLabel11.setText("Tipo");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(590, 330, 70, 30);

        scroll.setBorder(new javax.swing.border.MatteBorder(null));
        scroll.setViewportView(Mostrador);

        getContentPane().add(scroll);
        scroll.setBounds(30, 360, 830, 290);
        scroll.setViewportView(Mostrador);
        scroll.getViewport().setView(Mostrador);

        setBounds(0, 0, 1091, 726);
    }// </editor-fold>//GEN-END:initComponents

    private void boton_imagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_imagenActionPerformed
        JFileChooser seleccion =new JFileChooser();
        FileNameExtensionFilter filtro=new FileNameExtensionFilter(".PNG",".png");
        seleccion.setFileFilter(filtro);
        seleccion.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int resultado= seleccion.showOpenDialog(this);
        if(resultado==JFileChooser.APPROVE_OPTION){
            File nombre=seleccion.getSelectedFile();
            
            ImageIcon imagen = new ImageIcon(seleccion.getSelectedFile().getPath());
            pathactual=seleccion.getSelectedFile().getPath();
            int y=imagenaqui.getWidth();
            int x=imagenaqui.getHeight();
            ImageIcon imagenredimencionada= new ImageIcon(imagen.getImage().getScaledInstance(x, y,0));
            imagenaqui.setIcon(imagenredimencionada);
            
            
//            iba aqu[i que quiero mostrar las plantas creadas en el panel de a la par :v :v :V
            // AHhhh y arreglar que para borra nodos :v :V :V
            
        }
        
        
       
        
    }//GEN-LAST:event_boton_imagenActionPerformed
    public void mostrar(nodo_planta nuevo){
        String nombre=nuevo.nombre;
        String tipo=nuevo.tipo;
        String paht=nuevo.pathimagen;
        int  ataque=nuevo.ataque;
        int defensa=nuevo.defensa;
        Mostrador.setLayout(null);
        JLabel mnombre= new JLabel(); mnombre.setText(nombre);Mostrador.add(mnombre); mnombre.setBounds(120,mostradory,130,30);
        JLabel mataque= new JLabel(); mataque.setText(String.valueOf(ataque));Mostrador.add(mataque); mataque.setBounds(270,mostradory,130,30);
        JLabel mdefensa=new JLabel(); mdefensa.setText(String.valueOf(defensa)); Mostrador.add(mdefensa);mdefensa.setBounds(410,mostradory,130,30);
        JLabel mtipo= new JLabel(); mtipo.setText(tipo);Mostrador.add(mtipo); mtipo.setBounds(560,mostradory,130,30);
        JButton eliminar=new JButton(); eliminar.setText("Eliminar");Mostrador.add(eliminar); eliminar.setBounds(690,mostradory,100,20);
        JButton modificar=new JButton(); modificar.setText("Modificar");Mostrador.add(modificar);modificar.setBounds(690,mostradory+20,100,20);
        JLabel mimagen=new JLabel();Mostrador.add(mimagen);mimagen.setBounds(10,mostradory+20,100,100);
        ImageIcon imagen = new ImageIcon(pathactual);
        ImageIcon imagenredimencionada= new ImageIcon(imagen.getImage().getScaledInstance(100, 100,0));
        mimagen.setIcon(imagenredimencionada);
        mostradory+=100;
        
       }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombre=nombre_planta.getText();
        int ataque= Integer.valueOf(lista_ataque.getSelectedItem().toString());
        int defensa= Integer.valueOf(lista_defensa.getSelectedItem().toString());
        String tipo=lista_tipo.getSelectedItem().toString();

        nuevaplanta=new nodo_planta(nombre,pathactual,ataque,defensa,tipo);
        PlantasvsZombis.plantas.insertar(nuevaplanta);
        limpiar();
        mostrar(nuevaplanta);
        
   
    
    
    }//GEN-LAST:event_jButton1ActionPerformed
   public void limpiar(){
    nombre_planta.setText("");
    lista_ataque.setSelectedIndex(0);
    lista_defensa.setSelectedIndex(0);
    lista_tipo.setSelectedIndex(0);
    imagenaqui.setIcon(null);
   }
   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCreacionPlantas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCreacionPlantas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCreacionPlantas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCreacionPlantas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCreacionPlantas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Mostrador;
    private javax.swing.JButton boton_imagen;
    private javax.swing.JLabel imagenaqui;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox lista_ataque;
    private javax.swing.JComboBox lista_defensa;
    private javax.swing.JComboBox lista_tipo;
    private javax.swing.JTextField nombre_planta;
    private static javax.swing.JScrollPane scroll;
    // End of variables declaration//GEN-END:variables
}
