/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package plantasvszombis;

import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Erick
 */
public class MenuCreacionPlantas extends javax.swing.JFrame {

    /**
     * Creates new form MenuCreacionPlantas
     */
    public MenuCreacionPlantas() {
        initComponents();
        for(int x=1;x<100;x++){
        lista_defensa.addItem(x);
        lista_ataque.addItem(x);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        imagenaqui = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nombre_planta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lista_ataque = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        lista_defensa = new javax.swing.JComboBox();
        boton_imagen = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        Mostrador = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PlantasVsZombis 1.0.0");
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel2.setText("Imagen");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 20, 70, 30);

        imagenaqui.setBackground(new java.awt.Color(153, 153, 255));
        imagenaqui.setText("Su imagen Aquí :v");
        jPanel1.add(imagenaqui);
        imagenaqui.setBounds(320, 20, 180, 150);

        jLabel4.setText("Nombre");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 80, 70, 30);
        jPanel1.add(nombre_planta);
        nombre_planta.setBounds(120, 80, 160, 30);

        jLabel5.setText("Puntos de Ataque");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 120, 100, 30);

        jPanel1.add(lista_ataque);
        lista_ataque.setBounds(120, 130, 120, 20);

        jLabel6.setText("Puntos de Defensa");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 160, 100, 30);

        jPanel1.add(lista_defensa);
        lista_defensa.setBounds(120, 170, 120, 20);

        boton_imagen.setText("Elegir Imagen");
        boton_imagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_imagenActionPerformed(evt);
            }
        });
        jPanel1.add(boton_imagen);
        boton_imagen.setBounds(120, 20, 160, 40);

        jLabel7.setText("Tipo de  Ataque");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 200, 100, 30);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Disparador", "Ataque Directo" }));
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(120, 210, 120, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 70, 530, 240);

        jLabel1.setText("Menú De Creación de Personajes  Plantas");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 10, 340, 50);

        Mostrador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(Mostrador);
        Mostrador.setBounds(560, 20, 490, 480);

        setBounds(0, 0, 1091, 619);
    }// </editor-fold>//GEN-END:initComponents

    private void boton_imagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_imagenActionPerformed
        JFileChooser seleccion =new JFileChooser();
        FileNameExtensionFilter filtro=new FileNameExtensionFilter(".jpg",".png");
        seleccion.setFileFilter(filtro);
        seleccion.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int resultado= seleccion.showOpenDialog(this);
        if(resultado==JFileChooser.APPROVE_OPTION){
            File nombre=seleccion.getSelectedFile();
            
            ImageIcon imagen = new ImageIcon(seleccion.getSelectedFile().getPath());
            ImageIcon imagenredimencionada= new ImageIcon(imagen.getImage().getScaledInstance(20, 20,20));
            imagenaqui.setIcon(imagenredimencionada);
        }
        
        
        seleccion.showDialog(this, "Elija la imagen de su nueva planta");
        
    }//GEN-LAST:event_boton_imagenActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCreacionPlantas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCreacionPlantas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCreacionPlantas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCreacionPlantas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCreacionPlantas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Mostrador;
    private javax.swing.JButton boton_imagen;
    private javax.swing.JLabel imagenaqui;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox lista_ataque;
    private javax.swing.JComboBox lista_defensa;
    private javax.swing.JTextField nombre_planta;
    // End of variables declaration//GEN-END:variables
}
